version: "3.6"
services:
  db:
    image: mysql:5.7
    container_name: go_sample
    volumes:
      - ./mysql/conf:/etc/mysql/conf.db
      - ./mysql/data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: gqlgen_tutorial
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: hoge
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      TZ: "Asia/Tokyo"
